version: '3'
services:
  db:
    image: mongo
    restart: always
    volumes:
      - ./data-node:/data/db
    ports:
      - ${MONGO_PORT}:27017
    command: mongod --noauth --smallfiles

  front:
    build:
      context: front-end/.
    ports:
      - ${FRONT_PORT}:3000
    depends_on:
      - api

  api:
    build:
      context: back-node/.
    restart: always
    ports:
      - ${API_PORT}:4000
    links:
      - db:db
    depends_on:
      - db
