version: '3'
services:
  db:
    image: mongo:4.0
    restart: always
    ports:
      - ${MONGO_PORT}:27017

  front:
    build:
      context: front-end/.
    ports:
      - ${FRONT_PORT}:3000
    depends_on:
      - api

  api:
    build:
      context: back-node/.
    restart: always
    ports:
      - ${API_PORT}:4000
    links:
      - db
    depends_on:
      - db
