FROM node
WORKDIR /app
COPY package*.json /app/
RUN npm config set proxy http://proxy.fr.auchan.com:80
RUN npm config set https-proxy http://proxy.fr.auchan.com:80
RUN npm install
COPY ./ /app/
EXPOSE 3000
CMD [ "npm", "run", "recette", "--prod" ]